### ISSUE TITLE
"you must set"

### ISSUE THREAD

**Issue by StanMOI** [mitchellcairns/gbc-rgb-led-2.0#1]
Hi,
You say:
_For flashing this to an Attiny85, you must set:
efuse: 0xff
hfuse: 0xdf
lfuse: 0xE2_

You must set...But what and Where ?

And also, 
or what use is folder with name "firmware" ?

Thank you for answer

**Comment by mitchellcairns** [comment]
Hi, you can use a tool such as avrdude to flash the appropriate fuse values.

https://dntruong.wordpress.com/2015/07/08/setting-and-reading-attiny85-fuses/

That's an example of how you could do it. Any programmer you use should work.
